# Country Club Analysis with SQL 

Our new country club has been open for 3 months! It's time to analyze the data from our first quarter and evaulate the state of the business. 

In [1]:
# Import packages

import pandas as pd
import sqlite3

In [2]:
# Connect to database

conn = sqlite3.connect("country_club_database.db")
cur = conn.cursor() 

In [3]:
# View all tables in database

tables = cur.execute("SELECT name FROM sqlite_master WHERE type = 'table'").fetchall()

print(f'The following tables are in this database:')
for i in tables:
    print(i[0])


The following tables are in this database:
Bookings
Facilities
Members


Let's examine our  3 tables:

In [4]:
# The facilities table

query = ''' SELECT *
            FROM facilities;
        '''

df_facil = pd.read_sql_query(query, conn)
df_facil.style.hide_index()
# df_facil.head()
print(df_facil.head())

   facid             name  membercost  guestcost  initialoutlay  \
0      0   Tennis Court 1         5.0       25.0          10000   
1      1   Tennis Court 2         5.0       25.0           8000   
2      2  Badminton Court         0.0       15.5           4000   
3      3     Table Tennis         0.0        5.0            320   
4      4   Massage Room 1         9.9       80.0           4000   

   monthlymaintenance  
0                 200  
1                 200  
2                  50  
3                  10  
4                3000  


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\2171247462.py:8: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_facil.style.hide_index()


In [5]:
df_facil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   facid               9 non-null      int64  
 1   name                9 non-null      object 
 2   membercost          9 non-null      float64
 3   guestcost           9 non-null      float64
 4   initialoutlay       9 non-null      int64  
 5   monthlymaintenance  9 non-null      int64  
dtypes: float64(2), int64(3), object(1)
memory usage: 560.0+ bytes


In [6]:
# The Booking table

query = ''' SELECT *
            FROM Bookings;
        '''

df_Booking = pd.read_sql_query(query, conn)
df_Booking.style.hide_index()
print(df_Booking.head())

   bookid  facid  memid            starttime  slots
0       0      3      1  2012-07-03 11:00:00      2
1       1      4      1  2012-07-03 08:00:00      2
2       2      6      0  2012-07-03 18:00:00      2
3       3      7      1  2012-07-03 19:00:00      2
4       4      8      1  2012-07-03 10:00:00      1


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\2334768658.py:8: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Booking.style.hide_index()


In [7]:
df_Booking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4043 entries, 0 to 4042
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   bookid     4043 non-null   int64 
 1   facid      4043 non-null   int64 
 2   memid      4043 non-null   int64 
 3   starttime  4043 non-null   object
 4   slots      4043 non-null   int64 
dtypes: int64(4), object(1)
memory usage: 158.1+ KB


In [8]:
# The Booking table

query = ''' SELECT *
            FROM Members;
        '''

df_Members= pd.read_sql_query(query, conn)
df_Members.style.hide_index()
print(df_Members.head())

   memid   surname firstname                       address  zipcode  \
0      0     GUEST     GUEST                         GUEST        0   
1      1     Smith    Darren    8 Bloomsbury Close, Boston     4321   
2      2     Smith     Tracy  8 Bloomsbury Close, New York     4321   
3      3    Rownam       Tim        23 Highway Way, Boston    23423   
4      4  Joplette    Janice    20 Crossing Road, New York      234   

        telephone recommendedby             joindate  
0  (000) 000-0000                2012-07-01 00:00:00  
1    555-555-5555                2012-07-02 12:02:05  
2    555-555-5555                2012-07-02 12:08:23  
3  (844) 693-0723                2012-07-03 09:32:15  
4  (833) 942-4710             1  2012-07-03 10:25:05  


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\2963622129.py:8: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Members.style.hide_index()


In [9]:
df_Members.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   memid          31 non-null     int64 
 1   surname        31 non-null     object
 2   firstname      31 non-null     object
 3   address        31 non-null     object
 4   zipcode        31 non-null     int64 
 5   telephone      31 non-null     object
 6   recommendedby  31 non-null     object
 7   joindate       31 non-null     object
dtypes: int64(2), object(6)
memory usage: 2.1+ KB


In [10]:
df_Members.head()

memid   surname firstname                       address  zipcode  \
0      0     GUEST     GUEST                         GUEST        0   
1      1     Smith    Darren    8 Bloomsbury Close, Boston     4321   
2      2     Smith     Tracy  8 Bloomsbury Close, New York     4321   
3      3    Rownam       Tim        23 Highway Way, Boston    23423   
4      4  Joplette    Janice    20 Crossing Road, New York      234   

        telephone recommendedby             joindate  
0  (000) 000-0000                2012-07-01 00:00:00  
1    555-555-5555                2012-07-02 12:02:05  
2    555-555-5555                2012-07-02 12:08:23  
3  (844) 693-0723                2012-07-03 09:32:15  
4  (833) 942-4710             1  2012-07-03 10:25:05

In [11]:
# data3['Title'] = pd.to_numeric(data3['Title'])
df_Members["recommendedby"] = pd.to_numeric(df_Members["recommendedby"])
print(df_Members.dtypes)

memid              int64
surname           object
firstname         object
address           object
zipcode            int64
telephone         object
recommendedby    float64
joindate          object
dtype: object


In [12]:
df_Members.head()

memid   surname firstname                       address  zipcode  \
0      0     GUEST     GUEST                         GUEST        0   
1      1     Smith    Darren    8 Bloomsbury Close, Boston     4321   
2      2     Smith     Tracy  8 Bloomsbury Close, New York     4321   
3      3    Rownam       Tim        23 Highway Way, Boston    23423   
4      4  Joplette    Janice    20 Crossing Road, New York      234   

        telephone  recommendedby             joindate  
0  (000) 000-0000            NaN  2012-07-01 00:00:00  
1    555-555-5555            NaN  2012-07-02 12:02:05  
2    555-555-5555            NaN  2012-07-02 12:08:23  
3  (844) 693-0723            NaN  2012-07-03 09:32:15  
4  (833) 942-4710            1.0  2012-07-03 10:25:05

2. Write a Pandas program to display all the facid from locations facilities and SQL

In [13]:
df_facil['facid'].head(10)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
Name: facid, dtype: int64

In [14]:
query = ''' SELECT facid
            FROM facilities;
        '''

df_facil_facid = pd.read_sql_query(query, conn)
df_facil_facid.style.hide_index()
# df_facil.head()
print(df_facil_facid)

   facid
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\3135148217.py:6: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_facil_facid.style.hide_index()


3. Write a Pandas program to extract the first 7 records from Bookings

In [15]:
df_Booking.head(7)

bookid  facid  memid            starttime  slots
0       0      3      1  2012-07-03 11:00:00      2
1       1      4      1  2012-07-03 08:00:00      2
2       2      6      0  2012-07-03 18:00:00      2
3       3      7      1  2012-07-03 19:00:00      2
4       4      8      1  2012-07-03 10:00:00      1
5       5      8      1  2012-07-03 15:00:00      1
6       6      0      2  2012-07-04 09:00:00      3

In [16]:
# The Booking table

query = ''' SELECT *
            FROM Bookings LIMIT 7;
        '''

df_Booking_7 = pd.read_sql_query(query, conn)
df_Booking_7.style.hide_index()
print(df_Booking_7)

   bookid  facid  memid            starttime  slots
0       0      3      1  2012-07-03 11:00:00      2
1       1      4      1  2012-07-03 08:00:00      2
2       2      6      0  2012-07-03 18:00:00      2
3       3      7      1  2012-07-03 19:00:00      2
4       4      8      1  2012-07-03 10:00:00      1
5       5      8      1  2012-07-03 15:00:00      1
6       6      0      2  2012-07-04 09:00:00      3


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\1570582284.py:8: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Booking_7.style.hide_index()


4. Write a Pandas program to select distinct facilities name  from facilities file. 

In [17]:
print("Distinct facility name:")
print(df_facil.name.unique())

Distinct facility name:
['Tennis Court 1' 'Tennis Court 2' 'Badminton Court' 'Table Tennis'
 'Massage Room 1' 'Massage Room 2' 'Squash Court' 'Snooker Table'
 'Pool Table']


In [18]:
# The facilities table

query = ''' SELECT DISTINCT name
            FROM facilities;
        '''

df_facil_dname = pd.read_sql_query(query, conn)
df_facil_dname.style.hide_index()
# df_facil.head()
print(df_facil_dname)

              name
0   Tennis Court 1
1   Tennis Court 2
2  Badminton Court
3     Table Tennis
4   Massage Room 1
5   Massage Room 2
6     Squash Court
7    Snooker Table
8       Pool Table


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\382987362.py:8: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_facil_dname.style.hide_index()


In [19]:
# df_facil['facid'].value_counts()
# df_facil.groupby('facid').count()
# df_facil['facid']= df_facil.sum()
df_facil.nunique()

facid                 9
name                  9
membercost            4
guestcost             5
initialoutlay         7
monthlymaintenance    6
dtype: int64

In [20]:
print("Distinct facility name:")
print(df_facil.name.unique())

Distinct facility name:
['Tennis Court 1' 'Tennis Court 2' 'Badminton Court' 'Table Tennis'
 'Massage Room 1' 'Massage Room 2' 'Squash Court' 'Snooker Table'
 'Pool Table']


In [21]:
# The facilities table

query = ''' SELECT DISTINCT name
            FROM facilities;
        '''

df_facil_dist_name = pd.read_sql_query(query, conn)
df_facil_dist_name.style.hide_index()
# df_facil.head()
print(df_facil_dist_name)

              name
0   Tennis Court 1
1   Tennis Court 2
2  Badminton Court
3     Table Tennis
4   Massage Room 1
5   Massage Room 2
6     Squash Court
7    Snooker Table
8       Pool Table


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\597316958.py:8: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_facil_dist_name.style.hide_index()


5. Write a Pandas program to display the first and last name, and member id number for all members surname is "Mackenzie". 

In [22]:
print("surname  firstname    memid")
result = df_Members[df_Members.surname == 'Mackenzie']
for index, row in result.iterrows():
    print(row['surname'],'   ',row['firstname'],'       ',row['memid'])

surname  firstname    memid
Mackenzie     Anna         21


In [23]:
# The Members table

query = ''' SELECT firstname, surname, memid
             FROM Members
              WHERE surname = 'Mackenzie';
        '''

df_Member_namemid = pd.read_sql_query(query, conn)
df_Member_namemid.style.hide_index()
# df_facil.head()
print(df_Member_namemid)

  firstname    surname  memid
0      Anna  Mackenzie     21


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\1393080683.py:9: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Member_namemid.style.hide_index()


6. Write a Pandas program to display the firstname, surname, zipcode and member id for those members whose first name starts with the letter 'S'

In [24]:
print("Firstname       surname      zipcode    member ID")
result = df_Members[df_Members['surname'].str[:1]=='S']
for index, row in result.iterrows():
    print(row['firstname'].ljust(15),row['surname'].ljust(15),str(row['zipcode']).ljust(9),row['memid'])

Firstname       surname      zipcode    member ID
Darren          Smith           4321      1
Tracy           Smith           4321      2
Ponder          Stibbons        87630     9
Jack            Smith           69302     14
Ramnaresh       Sarwin          65464     24
Darren          Smith           66796     37


In [25]:
# The Members table

query = ''' SELECT firstname, surname, zipcode, memid
             FROM Members
              WHERE surname LIKE 'S%';
        '''

df_Member_namemids = pd.read_sql_query(query, conn)
df_Member_namemids.style.hide_index()
# df_facil.head()
print(df_Member_namemids)

   firstname   surname  zipcode  memid
0     Darren     Smith     4321      1
1      Tracy     Smith     4321      2
2     Ponder  Stibbons    87630      9
3       Jack     Smith    69302     14
4  Ramnaresh    Sarwin    65464     24
5     Darren     Smith    66796     37


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\677617439.py:9: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Member_namemids.style.hide_index()


7. Write a Pandas program to display the firstname, surname, zipcode and memberid number for those members whose first name does not contain the letter 'J'.

In [26]:
print("surname          Firstname      zipcode    member ID")

result = df_Members[df_Members['firstname'].str.find('J')==-1]
for index, row in result.iterrows():
    print(row['surname'].ljust(20),row['firstname'].ljust(10),str(row['zipcode']).ljust(10),row['memid'])


surname          Firstname      zipcode    member ID
GUEST                GUEST      0          0
Smith                Darren     4321       1
Smith                Tracy      4321       2
Rownam               Tim        23423      3
Butters              Gerald     56754      5
Tracy                Burton     45678      6
Dare                 Nancy      10383      7
Boothe               Tim        234        8
Stibbons             Ponder     87630      9
Owen                 Charles    28563      10
Jones                David      33862      11
Baker                Anne       80743      12
Bader                Florence   84923      15
Baker                Timothy    58393      16
Pinker               David      65332      17
Genting              Matthew    52365      20
Mackenzie            Anna       64577      21
Sarwin               Ramnaresh  65464      24
Jones                Douglas    11986      26
Rumney               Henrietta  78533      27
Farrell              David      4353

In [27]:
# The Members table

query = ''' SELECT surname, firstname, zipcode, memid
             FROM Members
              WHERE firstname NOT LIKE '%J%';
        '''

df_Member_namemidj = pd.read_sql_query(query, conn)
df_Member_namemidj.style.hide_index()
# df_facil.head()
print(df_Member_namemidj)

              surname  firstname  zipcode  memid
0               GUEST      GUEST        0      0
1               Smith     Darren     4321      1
2               Smith      Tracy     4321      2
3              Rownam        Tim    23423      3
4             Butters     Gerald    56754      5
5               Tracy     Burton    45678      6
6                Dare      Nancy    10383      7
7              Boothe        Tim      234      8
8            Stibbons     Ponder    87630      9
9                Owen    Charles    28563     10
10              Jones      David    33862     11
11              Baker       Anne    80743     12
12              Bader   Florence    84923     15
13              Baker    Timothy    58393     16
14             Pinker      David    65332     17
15            Genting    Matthew    52365     20
16          Mackenzie       Anna    64577     21
17             Sarwin  Ramnaresh    65464     24
18              Jones    Douglas    11986     26
19             Rumne

C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\699992041.py:9: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Member_namemidj.style.hide_index()


8. Write a Pandas program to display the first name, surname, zipcode and memid in ascending order by zipcode. 

In [28]:
print("First name       surname      zipcode    memid")
result = df_Members.sort_values('zipcode', ascending=True)
for index, row in result.iterrows():
    print(row['firstname'].ljust(15),row['surname'].ljust(19),str(row['zipcode']).ljust(9),row['memid'])

First name       surname      zipcode    memid
GUEST           GUEST               0         0
Janice          Joplette            234       4
Tim             Boothe              234       8
Darren          Smith               4321      1
Tracy           Smith               4321      2
Nancy           Dare                10383     7
Douglas         Jones               11986     26
Tim             Rownam              23423     3
Charles         Owen                28563     10
David           Jones               33862     11
Millicent       Purview             34232     30
David           Farrell             43532     28
Joan            Coplin              43533     22
Burton          Tracy               45678     6
Matthew         Genting             52365     20
John            Hunt                54333     35
Gerald          Butters             56754     5
Jemima          Farrell             57392     13
Timothy         Baker               58393     16
Anna            Mackenzie      

In [29]:
# The Members table

query = ''' SELECT firstname, surname, zipcode, memid
             FROM Members
              ORDER BY zipcode;
        '''

df_Member_zcodes = pd.read_sql_query(query, conn)
df_Member_zcodes.style.hide_index()
# df_facil.head()
print(df_Member_zcodes)

    firstname            surname  zipcode  memid
0       GUEST              GUEST        0      0
1      Janice           Joplette      234      4
2         Tim             Boothe      234      8
3      Darren              Smith     4321      1
4       Tracy              Smith     4321      2
5       Nancy               Dare    10383      7
6     Douglas              Jones    11986     26
7         Tim             Rownam    23423      3
8     Charles               Owen    28563     10
9       David              Jones    33862     11
10  Millicent            Purview    34232     30
11      David            Farrell    43532     28
12       Joan             Coplin    43533     22
13     Burton              Tracy    45678      6
14    Matthew            Genting    52365     20
15       John               Hunt    54333     35
16     Gerald            Butters    56754      5
17     Jemima            Farrell    57392     13
18    Timothy              Baker    58393     16
19       Anna       

C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\1272697664.py:9: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Member_zcodes.style.hide_index()


9. Write a Pandas program to display the firstname, surname, zipcode and memid in descending order by firstname. 

In [30]:
print("First name       surname      zipcode    memid")
result = df_Members.sort_values('firstname', ascending=False)
for index, row in result.iterrows():
    print(row['firstname'].ljust(15),row['surname'].ljust(19),str(row['zipcode']).ljust(9),row['memid'])

First name       surname      zipcode    memid
Tracy           Smith               4321      2
Timothy         Baker               58393     16
Tim             Boothe              234       8
Tim             Rownam              23423     3
Ramnaresh       Sarwin              65464     24
Ponder          Stibbons            87630     9
Nancy           Dare                10383     7
Millicent       Purview             34232     30
Matthew         Genting             52365     20
John            Hunt                54333     35
Joan            Coplin              43533     22
Jemima          Farrell             57392     13
Janice          Joplette            234       4
Jack            Smith               69302     14
Hyacinth        Tupperware          68666     33
Henry           Worthington-Smyth   97676     29
Henrietta       Rumney              78533     27
Gerald          Butters             56754     5
GUEST           GUEST               0         0
Florence        Bader         

In [31]:
# The Members table

query = ''' SELECT firstname, surname, zipcode, memid
             FROM Members
              ORDER BY firstname DESC;
        '''

df_Member_orfname = pd.read_sql_query(query, conn)
df_Member_orfname.style.hide_index()
# df_facil.head()
print(df_Member_orfname)

    firstname            surname  zipcode  memid
0       Tracy              Smith     4321      2
1     Timothy              Baker    58393     16
2         Tim             Rownam    23423      3
3         Tim             Boothe      234      8
4   Ramnaresh             Sarwin    65464     24
5      Ponder           Stibbons    87630      9
6       Nancy               Dare    10383      7
7   Millicent            Purview    34232     30
8     Matthew            Genting    52365     20
9        John               Hunt    54333     35
10       Joan             Coplin    43533     22
11     Jemima            Farrell    57392     13
12     Janice           Joplette      234      4
13       Jack              Smith    69302     14
14   Hyacinth         Tupperware    68666     33
15      Henry  Worthington-Smyth    97676     29
16  Henrietta             Rumney    78533     27
17     Gerald            Butters    56754      5
18      GUEST              GUEST        0      0
19   Florence       

C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\4155574360.py:9: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Member_orfname.style.hide_index()


10. Write a Pandas program to display the first name, surname, recomendedby and memid where recommendedby are null. 

In [32]:
print("Firstname      surname       recommendedby    Mem ID")
result = df_Members[df_Members['recommendedby'].isnull()]
for index, row in result.iterrows():
    print(row['firstname'].ljust(15),row['surname'].ljust(15),str(row['recommendedby']).ljust(9),row['memid'])

Firstname      surname       recommendedby    Mem ID
GUEST           GUEST           nan       0
Darren          Smith           nan       1
Tracy           Smith           nan       2
Tim             Rownam          nan       3
Burton          Tracy           nan       6
Jemima          Farrell         nan       13
David           Farrell         nan       28
Hyacinth        Tupperware      nan       33
Darren          Smith           nan       37


In [33]:
# The Members table

query = ''' SELECT firstname, surname, recommendedby, memid
             FROM Members
              WHERE recommendedby IS NULL;
        '''

df_Member_rn = pd.read_sql_query(query, conn)
df_Member_rn.style.hide_index()
# df_facil.head()
print(df_Member_rn)

Empty DataFrame
Columns: [firstname, surname, recommendedby, memid]
Index: []


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\3476190733.py:9: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Member_rn.style.hide_index()


11. Write a Pandas program to display the first name, surname, recomendedby and member ide where recommendedby ids are not null. 

In [34]:
print("Firstname      surname       recommendedby    Mem ID")
result = df_Members[df_Members['recommendedby'].notnull()]
for index, row in result.iterrows():
    print(row['firstname'].ljust(15),row['surname'].ljust(15),str(row['recommendedby']).ljust(9),row['memid'])

Firstname      surname       recommendedby    Mem ID
Janice          Joplette        1.0       4
Gerald          Butters         1.0       5
Nancy           Dare            4.0       7
Tim             Boothe          3.0       8
Ponder          Stibbons        6.0       9
Charles         Owen            1.0       10
David           Jones           4.0       11
Anne            Baker           9.0       12
Jack            Smith           1.0       14
Florence        Bader           9.0       15
Timothy         Baker           13.0      16
David           Pinker          13.0      17
Matthew         Genting         5.0       20
Anna            Mackenzie       1.0       21
Joan            Coplin          16.0      22
Ramnaresh       Sarwin          15.0      24
Douglas         Jones           11.0      26
Henrietta       Rumney          20.0      27
Henry           Worthington-Smyth 2.0       29
Millicent       Purview         2.0       30
John            Hunt            30.0      35
Erica

In [35]:
# The Members table

query = ''' SELECT firstname, surname, recommendedby, memid
             FROM Members
              WHERE recommendedby IS NOT NULL;
        '''

df_Member_rnn = pd.read_sql_query(query, conn)
df_Member_rnn.style.hide_index()
# df_facil.head()
print(df_Member_rnn)

    firstname            surname recommendedby  memid
0       GUEST              GUEST                    0
1      Darren              Smith                    1
2       Tracy              Smith                    2
3         Tim             Rownam                    3
4      Janice           Joplette             1      4
5      Gerald            Butters             1      5
6      Burton              Tracy                    6
7       Nancy               Dare             4      7
8         Tim             Boothe             3      8
9      Ponder           Stibbons             6      9
10    Charles               Owen             1     10
11      David              Jones             4     11
12       Anne              Baker             9     12
13     Jemima            Farrell                   13
14       Jack              Smith             1     14
15   Florence              Bader             9     15
16    Timothy              Baker            13     16
17      David             Pi

C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\1073413841.py:9: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Member_rnn.style.hide_index()


12. Write a Pandas program to create and display a boolean series, where True for not null and False for null values or missing values in slot column of Bookings file. 

In [36]:
print("Original data / Slots")
print(df_Booking.slots)
print("\n\n   slots(Not null / Null Series")
print(df_Booking.slots.notnull())

Original data / Slots
0       2
1       2
2       2
3       2
4       1
       ..
4038    2
4039    1
4040    1
4041    1
4042    1
Name: slots, Length: 4043, dtype: int64


   slots(Not null / Null Series
0       True
1       True
2       True
3       True
4       True
        ... 
4038    True
4039    True
4040    True
4041    True
4042    True
Name: slots, Length: 4043, dtype: bool


There is no boolean data type in SQL Server. However, a common option is to use the BIT data type. A BIT data type is used to store bit values from 1 to 64. So, a BIT field can be used for booleans, providing 1 for TRUE and 0 for FALSE.

13. Write a Pandas program to create a boolean series selecting rows with one or more nulls from locations file. 

In [37]:
print(df_Booking.isnull())

      bookid  facid  memid  starttime  slots
0      False  False  False      False  False
1      False  False  False      False  False
2      False  False  False      False  False
3      False  False  False      False  False
4      False  False  False      False  False
...      ...    ...    ...        ...    ...
4038   False  False  False      False  False
4039   False  False  False      False  False
4040   False  False  False      False  False
4041   False  False  False      False  False
4042   False  False  False      False  False

[4043 rows x 5 columns]


14. Write a Pandas program to count the NaN values of all the columns of Booking file. 

In [38]:
print("\nNaN values of all the columns of Booking file:" )
print(df_Booking.isna().sum())


NaN values of all the columns of Booking file:
bookid       0
facid        0
memid        0
starttime    0
slots        0
dtype: int64


15. Write a Pandas program to display the first name, surname, joindate and department memid for those members whose first name ends with the letter 'm'.

In [39]:
print("First name       surname      joindate    memberid")
result = df_Members[df_Members['firstname'].str[-1]=='m']
for index, row in result.iterrows():
    print(row['firstname'].ljust(15),row['surname'].ljust(15),str(row['joindate']).ljust(9),row['memid'])

First name       surname      joindate    memberid
Tim             Rownam          2012-07-03 09:32:15 3
Tim             Boothe          2012-07-25 16:02:35 8


In [40]:
# The Members table

query = ''' SELECT firstname, surname, joindate, memid
             FROM Members
              WHERE firstname LIKE '%m';
        '''

df_Member_m = pd.read_sql_query(query, conn)
df_Member_m.style.hide_index()
# df_facil.head()
print(df_Member_m)

  firstname surname             joindate  memid
0       Tim  Rownam  2012-07-03 09:32:15      3
1       Tim  Boothe  2012-07-25 16:02:35      8


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\81678176.py:9: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Member_m.style.hide_index()


16. Write a Pandas program to display the firstname, surname, zipcode and memid for those members whose first name ends with the letter 'd' or 'n' or 's' and also arrange the result in descending order by memid. 

In [41]:
print("First name       surname      zipcode    memberid")
result = df_Members[df_Members['firstname'].str[-1].isin(['s','d','n'])]
result = result.sort_values('memid', ascending=False)
for index, row in result.iterrows():
    print(row['firstname'].ljust(15),row['surname'].ljust(15),str(row['zipcode']).ljust(9),row['memid'])

First name       surname      zipcode    memberid
Darren          Smith           66796     37
John            Hunt            54333     35
David           Farrell         43532     28
Douglas         Jones           11986     26
Joan            Coplin          43533     22
David           Pinker          65332     17
David           Jones           33862     11
Charles         Owen            28563     10
Burton          Tracy           45678     6
Gerald          Butters         56754     5
Darren          Smith           4321      1


In [42]:
# The Members table

query = ''' SELECT firstname, surname, zipcode, memid
             FROM Members
              WHERE firstname LIKE '%d'
              OR firstname LIKE '%s'
              OR firstname LIKE '%n'
               ORDER BY memid DESC;
        '''

df_Member_t = pd.read_sql_query(query, conn)
df_Member_t.style.hide_index()
# df_facil.head()
print(df_Member_t)

   firstname  surname  zipcode  memid
0     Darren    Smith    66796     37
1       John     Hunt    54333     35
2      David  Farrell    43532     28
3    Douglas    Jones    11986     26
4       Joan   Coplin    43533     22
5      David   Pinker    65332     17
6      David    Jones    33862     11
7    Charles     Owen    28563     10
8     Burton    Tracy    45678      6
9     Gerald  Butters    56754      5
10    Darren    Smith     4321      1


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\534068296.py:12: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Member_t.style.hide_index()


17. Write a Pandas program to display the first name, surname, zipcode and memid for members who have a zipcode either in department 4321 or 45678. 

In [43]:
print("First name      surname       zipcode    memid ")
result = df_Members[df_Members['zipcode'].isin([4321, 45678])]

for index, row in result.iterrows():
    print(row['firstname'].ljust(15),row['surname'].ljust(15),str(row['zipcode']).ljust(9),row['memid'])

First name      surname       zipcode    memid 
Darren          Smith           4321      1
Tracy           Smith           4321      2
Burton          Tracy           45678     6


In [44]:
# The Members table

query = ''' SELECT firstname, surname, zipcode, memid
             FROM Members
              WHERE zipcode IN (4321, 45678);
        '''

df_Member_t = pd.read_sql_query(query, conn)
df_Member_t.style.hide_index()
# df_facil.head()
print(df_Member_t)

  firstname surname  zipcode  memid
0    Darren   Smith     4321      1
1     Tracy   Smith     4321      2
2    Burton   Tracy    45678      6


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\1612108275.py:9: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Member_t.style.hide_index()


18. Write a Pandas program to display the first name, surname, zipcode and memid for those members whose recommendedby members that hold the ID 1,2,3

In [45]:
print("First name      surname       recommendedby    memid")
# df_Members['recommendedby'] = df_Members['recommendedby'].fillna(0)
result = df_Members[df_Members['recommendedby'].isin([1,2,4])]

for index, row in result.iterrows():
    print(row['firstname'].ljust(15),row['surname'].ljust(20),str(row['recommendedby']).ljust(12),row['memid'])

First name      surname       recommendedby    memid
Janice          Joplette             1.0          4
Gerald          Butters              1.0          5
Nancy           Dare                 4.0          7
Charles         Owen                 1.0          10
David           Jones                4.0          11
Jack            Smith                1.0          14
Anna            Mackenzie            1.0          21
Henry           Worthington-Smyth    2.0          29
Millicent       Purview              2.0          30
Erica           Crumpet              2.0          36


In [46]:
# The Members table

query = ''' SELECT firstname, surname, recommendedby, memid
             FROM Members
              WHERE recommendedby IN (1, 2, 4);
        '''

df_Member_rb = pd.read_sql_query(query, conn)
df_Member_rb.style.hide_index()
# df_facil.head()
print(df_Member_rb)

   firstname            surname recommendedby  memid
0     Janice           Joplette             1      4
1     Gerald            Butters             1      5
2      Nancy               Dare             4      7
3    Charles               Owen             1     10
4      David              Jones             4     11
5       Jack              Smith             1     14
6       Anna          Mackenzie             1     21
7      Henry  Worthington-Smyth             2     29
8  Millicent            Purview             2     30
9      Erica            Crumpet             2     36


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\136666999.py:9: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Member_rb.style.hide_index()


19. Write a Pandas program to display the first, last name, salary and department number for those employees who holds a letter n as a 3rd character in their first name. 

In [47]:
print("First name      surname      recommendedby  memid")
result = df_Members[df_Members['firstname'].str[2:3]=='n']
for index, row in result.iterrows():
    print(row['firstname'].ljust(15),row['surname'].ljust(15),str(row['recommendedby']).ljust(9),row['memid'])

First name      surname      recommendedby  memid
Janice          Joplette        1.0       4
Nancy           Dare            4.0       7
Ponder          Stibbons        6.0       9
Anne            Baker           9.0       12
Anna            Mackenzie       1.0       21
Henrietta       Rumney          20.0      27
Henry           Worthington-Smyth 2.0       29


In [48]:
# The Members table

query = ''' SELECT firstname, surname, recommendedby, memid
             FROM Members
              WHERE firstname LIKE "__n%";
        '''

df_Member_rn = pd.read_sql_query(query, conn)
df_Member_rn.style.hide_index()
# df_facil.head()
print(df_Member_rn)


   firstname            surname recommendedby  memid
0     Janice           Joplette             1      4
1      Nancy               Dare             4      7
2     Ponder           Stibbons             6      9
3       Anne              Baker             9     12
4       Anna          Mackenzie             1     21
5  Henrietta             Rumney            20     27
6      Henry  Worthington-Smyth             2     29


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\3262840714.py:9: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Member_rn.style.hide_index()


20. Write a Pandas program to display the firstname, surname, zipcode and memid for those members not recommended in the departments 1,3 and 5

In [49]:
print("First name      surname   recommendedby  memid")
result = df_Members[df_Members['recommendedby'].isin([1,3,4])]
for index, row in result.iterrows():
    print(row['firstname'].ljust(15),row['surname'].ljust(15),str(row['recommendedby']).ljust(9),row['memid'])

First name      surname   recommendedby  memid
Janice          Joplette        1.0       4
Gerald          Butters         1.0       5
Nancy           Dare            4.0       7
Tim             Boothe          3.0       8
Charles         Owen            1.0       10
David           Jones           4.0       11
Jack            Smith           1.0       14
Anna            Mackenzie       1.0       21


In [50]:
# The Members table

query = ''' SELECT firstname, surname, recommendedby, memid
             FROM Members
              WHERE recommendedby IN (1,3,4);
        '''

df_Member_rn = pd.read_sql_query(query, conn)
df_Member_rn.style.hide_index()
# df_facil.head()
print(df_Member_rn)


  firstname    surname recommendedby  memid
0    Janice   Joplette             1      4
1    Gerald    Butters             1      5
2     Nancy       Dare             4      7
3       Tim     Boothe             3      8
4   Charles       Owen             1     10
5     David      Jones             4     11
6      Jack      Smith             1     14
7      Anna  Mackenzie             1     21


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\2409689101.py:9: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Member_rn.style.hide_index()


21. Write a Pandas program to display the ID for those memembers who did 100 or more Booking in the past. 

In [51]:
result = df_Booking.groupby(['memid']) 
print(result.filter(lambda x: len(x) > 100).groupby('memid').size().sort_values(ascending=False))

memid
0     883
3     408
1     261
2     210
8     188
6     176
16    166
5     163
4     159
10    131
21    126
15    120
12    118
7     117
11    115
9     104
dtype: int64


In [52]:
# The Members table
# SELECT age, count(age) 
#   FROM Students 
#  GROUP by age

query = ''' SELECT memid, count(memid)
             FROM Bookings
                  GROUP BY memid
                     HAVING COUNT(*) >=100;
        '''

df_Booking_cnt = pd.read_sql_query(query, conn)
df_Booking_cnt.style.hide_index()
# df_facil.head()
print(df_Booking_cnt)

    memid  count(memid)
0       0           883
1       1           261
2       2           210
3       3           408
4       4           159
5       5           163
6       6           176
7       7           117
8       8           188
9       9           104
10     10           131
11     11           115
12     12           118
13     15           120
14     16           166
15     21           126


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\3175179579.py:13: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Booking_cnt.style.hide_index()


22. Write a Pandas program to calculate minimum, maximum and mean cost from guestcost file. 

In [53]:
print(df_facil.agg({'membercost': ['min', 'max', 'mean', 'median']}))

        membercost
min            0.0
max            9.9
mean           3.7
median         3.5


In [54]:
df_facil.describe()

facid  membercost  guestcost  initialoutlay  monthlymaintenance
count  9.000000    9.000000   9.000000       9.000000            9.000000
mean   4.000000    3.700000  28.666667    4018.888889          730.000000
std    2.738613    4.108832  30.156881    3393.038625         1289.057311
min    0.000000    0.000000   5.000000     320.000000           10.000000
25%    2.000000    0.000000   5.000000     450.000000           15.000000
50%    4.000000    3.500000  17.500000    4000.000000           80.000000
75%    6.000000    5.000000  25.000000    5000.000000          200.000000
max    8.000000    9.900000  80.000000   10000.000000         3000.000000

In [55]:
# The Facilities table


query = ''' SELECT MIN(membercost), MAX(membercost), AVG(membercost)
             FROM Facilities;
        '''

df_facil_m = pd.read_sql_query(query, conn)
df_facil_m.style.hide_index()
# df_facil.head()
print(df_facil_m)

   MIN(membercost)  MAX(membercost)  AVG(membercost)
0                0              9.9              3.7


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\193693667.py:9: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_facil_m.style.hide_index()


23. Write a Pandas program to display the details of facilities in descending sequence on name. 

In [56]:
print("name             facid        membercost    guestcost")
result = df_facil.sort_values('name')
for index, row in result.iterrows():
    print(row['name'].ljust(20),str(row['facid']).ljust(10),str(row['membercost']).ljust(10),row['guestcost'])

name             facid        membercost    guestcost
Badminton Court      2          0.0        15.5
Massage Room 1       4          9.9        80.0
Massage Room 2       5          9.9        80.0
Pool Table           8          0.0        5.0
Snooker Table        7          0.0        5.0
Squash Court         6          3.5        17.5
Table Tennis         3          0.0        5.0
Tennis Court 1       0          5.0        25.0
Tennis Court 2       1          5.0        25.0


In [57]:
# The Booking table

query = ''' SELECT name, facid, membercost, guestcost
            FROM Facilities
            ORDER BY name ;
        '''

df_facilm = pd.read_sql_query(query, conn)
df_facilm.style.hide_index()
print(df_facilm)

              name  facid  membercost  guestcost
0  Badminton Court      2         0.0       15.5
1   Massage Room 1      4         9.9       80.0
2   Massage Room 2      5         9.9       80.0
3       Pool Table      8         0.0        5.0
4    Snooker Table      7         0.0        5.0
5     Squash Court      6         3.5       17.5
6     Table Tennis      3         0.0        5.0
7   Tennis Court 1      0         5.0       25.0
8   Tennis Court 2      1         5.0       25.0


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\2053367046.py:9: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_facilm.style.hide_index()


24. Write a Pandas program to display the first and last name and date of joining of the members who is either member or guest. 

In [58]:
from functools import reduce 
data_merge1 = reduce(lambda left , right:     # Merge three pandas DataFrames
                     pd.merge(left , right,
                              on = ["memid"]),
                     [df_Members, df_Booking ])
print(data_merge1)    

      memid  surname firstname                      address  zipcode  \
0         0    GUEST     GUEST                        GUEST        0   
1         0    GUEST     GUEST                        GUEST        0   
2         0    GUEST     GUEST                        GUEST        0   
3         0    GUEST     GUEST                        GUEST        0   
4         0    GUEST     GUEST                        GUEST        0   
...     ...      ...       ...                          ...      ...   
4038     36  Crumpet     Erica  Crimson Road, North Reading    75655   
4039     36  Crumpet     Erica  Crimson Road, North Reading    75655   
4040     36  Crumpet     Erica  Crimson Road, North Reading    75655   
4041     36  Crumpet     Erica  Crimson Road, North Reading    75655   
4042     36  Crumpet     Erica  Crimson Road, North Reading    75655   

           telephone  recommendedby             joindate  bookid  facid  \
0     (000) 000-0000            NaN  2012-07-01 00:00:00    

In [59]:
from functools import reduce 
merge_all = reduce(lambda left , right:     # Merge three pandas DataFrames
                     pd.merge(left , right,
                              on = ["facid"]),
                     [data_merge1, df_facil ])
print(merge_all)    

      memid  surname  firstname                                 address  \
0         0    GUEST      GUEST                                   GUEST   
1         0    GUEST      GUEST                                   GUEST   
2         0    GUEST      GUEST                                   GUEST   
3         0    GUEST      GUEST                                   GUEST   
4         0    GUEST      GUEST                                   GUEST   
...     ...      ...        ...                                     ...   
4038     30  Purview  Millicent  641 Drudgery Close, Burnington, Boston   
4039     30  Purview  Millicent  641 Drudgery Close, Burnington, Boston   
4040     35     Hunt       John               5 Bullington Lane, Boston   
4041     36  Crumpet      Erica             Crimson Road, North Reading   
4042     36  Crumpet      Erica             Crimson Road, North Reading   

      zipcode       telephone  recommendedby             joindate  bookid  \
0           0  (000) 0

In [60]:
merge_all.head()

memid surname firstname address  zipcode       telephone  recommendedby  \
0      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   
1      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   
2      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   
3      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   
4      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   

              joindate  bookid  facid            starttime  slots  \
0  2012-07-01 00:00:00       2      6  2012-07-03 18:00:00      2   
1  2012-07-01 00:00:00      11      6  2012-07-04 12:30:00      2   
2  2012-07-01 00:00:00      12      6  2012-07-04 14:00:00      2   
3  2012-07-01 00:00:00      22      6  2012-07-05 13:00:00      2   
4  2012-07-01 00:00:00      47      6  2012-07-07 08:30:00      2   

           name  membercost  guestcost  initialoutlay  monthlymaintenance  
0  Squash Court         3.5       17.5           5000                  80  
1  Squash Court         3.5       17.5           5000                  80  
2  Squash Court         3.5       17.5           5000                  80  
3  Squash Court         3.5       17.5           5000                  80  
4  Squash Court         3.5       17.5           5000                  80

In [61]:
merge_all.nunique()

memid                   30
surname                 25
firstname               27
address                 29
zipcode                 28
telephone               29
recommendedby           13
joindate                30
bookid                4043
facid                    9
starttime             1814
slots                    9
name                     9
membercost               4
guestcost                5
initialoutlay            7
monthlymaintenance       6
dtype: int64

In [62]:
merge_all['joindate'] = pd.to_datetime(merge_all['joindate'], format='%Y-%m-%d %H:%M')

In [63]:
merge_all['starttime'] = pd.to_datetime(merge_all['starttime'], format='%Y-%m-%d %H:%M')

In [64]:
merge_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4043 entries, 0 to 4042
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   memid               4043 non-null   int64         
 1   surname             4043 non-null   object        
 2   firstname           4043 non-null   object        
 3   address             4043 non-null   object        
 4   zipcode             4043 non-null   int64         
 5   telephone           4043 non-null   object        
 6   recommendedby       1975 non-null   float64       
 7   joindate            4043 non-null   datetime64[ns]
 8   bookid              4043 non-null   int64         
 9   facid               4043 non-null   int64         
 10  starttime           4043 non-null   datetime64[ns]
 11  slots               4043 non-null   int64         
 12  name                4043 non-null   object        
 13  membercost          4043 non-null   float64     

In [65]:
print(merge_all['joindate'].min())

2012-07-01 00:00:00


In [66]:
print(merge_all['joindate'].max())

2012-09-22 08:36:38


In [67]:
# The Booking table

query = ''' SELECT DISTINCT facid
            FROM Bookings;
        '''

df_Booking_distinct_facid = pd.read_sql_query(query, conn)
df_Booking_distinct_facid.style.hide_index()
print(df_Booking_distinct_facid)

   facid
0      3
1      4
2      6
3      7
4      8
5      0
6      1
7      2
8      5


C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\2171861169.py:8: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df_Booking_distinct_facid.style.hide_index()


There are a total of 9 facilities at the country club.

In [68]:
df_Members.nunique()

memid            31
surname          25
firstname        27
address          30
zipcode          29
telephone        30
recommendedby    13
joindate         31
dtype: int64

Our booking data spans from July 3, 2012 through September 30, 2012.

In [69]:
# Show member count 

query = '''SELECT COUNT(DISTINCT memid)
           FROM members
           WHERE memid != 0;
        '''

df = pd.read_sql_query(query, conn)
df.style.hide_index()

C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\1154457885.py:9: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df.style.hide_index()


We have 30 members and allow for guest visits.

Now let's write some queries to produce datasets of interest. 



In [70]:
print(merge_all.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4043 entries, 0 to 4042
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   memid               4043 non-null   int64         
 1   surname             4043 non-null   object        
 2   firstname           4043 non-null   object        
 3   address             4043 non-null   object        
 4   zipcode             4043 non-null   int64         
 5   telephone           4043 non-null   object        
 6   recommendedby       1975 non-null   float64       
 7   joindate            4043 non-null   datetime64[ns]
 8   bookid              4043 non-null   int64         
 9   facid               4043 non-null   int64         
 10  starttime           4043 non-null   datetime64[ns]
 11  slots               4043 non-null   int64         
 12  name                4043 non-null   object        
 13  membercost          4043 non-null   float64     

In [71]:
merge_all.head(2)

memid surname firstname address  zipcode       telephone  recommendedby  \
0      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   
1      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   

    joindate  bookid  facid           starttime  slots          name  \
0 2012-07-01       2      6 2012-07-03 18:00:00      2  Squash Court   
1 2012-07-01      11      6 2012-07-04 12:30:00      2  Squash Court   

   membercost  guestcost  initialoutlay  monthlymaintenance  
0         3.5       17.5           5000                  80  
1         3.5       17.5           5000                  80

In [72]:
merge_all["recommendedby"] = pd.to_numeric(merge_all["recommendedby"])
merge_all.head(2)

memid surname firstname address  zipcode       telephone  recommendedby  \
0      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   
1      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   

    joindate  bookid  facid           starttime  slots          name  \
0 2012-07-01       2      6 2012-07-03 18:00:00      2  Squash Court   
1 2012-07-01      11      6 2012-07-04 12:30:00      2  Squash Court   

   membercost  guestcost  initialoutlay  monthlymaintenance  
0         3.5       17.5           5000                  80  
1         3.5       17.5           5000                  80

In [73]:
merge_all["recommendedby"].fillna(0)
merge_all.head(2)

memid surname firstname address  zipcode       telephone  recommendedby  \
0      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   
1      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   

    joindate  bookid  facid           starttime  slots          name  \
0 2012-07-01       2      6 2012-07-03 18:00:00      2  Squash Court   
1 2012-07-01      11      6 2012-07-04 12:30:00      2  Squash Court   

   membercost  guestcost  initialoutlay  monthlymaintenance  
0         3.5       17.5           5000                  80  
1         3.5       17.5           5000                  80

In [74]:
# member=merge_all.loc[(merge_all['memid'] !=0)]
# member.head()

In [75]:
merge_all['member_total_cost']=merge_all['membercost']*merge_all['slots']
merge_all.head()

memid surname firstname address  zipcode       telephone  recommendedby  \
0      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   
1      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   
2      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   
3      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   
4      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   

    joindate  bookid  facid           starttime  slots          name  \
0 2012-07-01       2      6 2012-07-03 18:00:00      2  Squash Court   
1 2012-07-01      11      6 2012-07-04 12:30:00      2  Squash Court   
2 2012-07-01      12      6 2012-07-04 14:00:00      2  Squash Court   
3 2012-07-01      22      6 2012-07-05 13:00:00      2  Squash Court   
4 2012-07-01      47      6 2012-07-07 08:30:00      2  Squash Court   

   membercost  guestcost  initialoutlay  monthlymaintenance  member_total_cost  
0         3.5       17.5           5000                  80                7.0  
1         3.5       17.5           5000                  80                7.0  
2         3.5       17.5           5000                  80                7.0  
3         3.5       17.5           5000                  80                7.0  
4         3.5       17.5           5000                  80                7.0

In [76]:
merge_all['guest_total_cost']=merge_all['guestcost']*merge_all['slots']
merge_all.head()

memid surname firstname address  zipcode       telephone  recommendedby  \
0      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   
1      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   
2      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   
3      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   
4      0   GUEST     GUEST   GUEST        0  (000) 000-0000            NaN   

    joindate  bookid  facid           starttime  slots          name  \
0 2012-07-01       2      6 2012-07-03 18:00:00      2  Squash Court   
1 2012-07-01      11      6 2012-07-04 12:30:00      2  Squash Court   
2 2012-07-01      12      6 2012-07-04 14:00:00      2  Squash Court   
3 2012-07-01      22      6 2012-07-05 13:00:00      2  Squash Court   
4 2012-07-01      47      6 2012-07-07 08:30:00      2  Squash Court   

   membercost  guestcost  initialoutlay  monthlymaintenance  \
0         3.5       17.5           5000                  80   
1         3.5       17.5           5000                  80   
2         3.5       17.5           5000                  80   
3         3.5       17.5           5000                  80   
4         3.5       17.5           5000                  80   

   member_total_cost  guest_total_cost  
0                7.0              35.0  
1                7.0              35.0  
2                7.0              35.0  
3                7.0              35.0  
4                7.0              35.0

In [77]:
# create facilities level dataset
# df_facilities = pd.DataFrame(merge_all['facid'].unique())
# df_facilities.columns = ['facid']
# df_facilities.head()

In [78]:
# df_monetary = df.groupby('customer_id')['line_revenue'].sum().reset_index()
# df_monetary.columns = ['customer_id','monetary']
# df_customers = df_customers.merge(df_monetary, on='customer_id')
# df_customers.head()

In [79]:
df_memberfacil= merge_all.loc[(merge_all['memid'] !=0)].groupby('facid')['member_total_cost'].sum().reset_index()
df_memberfacil.head(10)


facid  member_total_cost
0      0             4785.0
1      1             4410.0
2      2                0.0
3      3                0.0
4      4             8751.6
5      5              534.6
6      6             1463.0
7      7                0.0
8      8                0.0

In [80]:
all_facil_memcost = df_memberfacil.sum(axis=0)
print(all_facil_memcost)

facid                   36.0
member_total_cost    19944.2
dtype: float64


In [81]:
df_guestfacil= merge_all.loc[(merge_all['memid'] ==0)].groupby('facid')['guest_total_cost'].sum().reset_index()
df_guestfacil.head(10)

facid  guest_total_cost
0      0            9075.0
1      1            9900.0
2      2            1906.5
3      3             180.0
4      4           41600.0
5      5           13920.0
6      6           12005.0
7      7             240.0
8      8             270.0

In [83]:
all_facil_guestcost = df_guestfacil.sum(axis=0)
print(all_facil_guestcost)

facid                  36.0
guest_total_cost    89096.5
dtype: float64


In [84]:
total_revenue=19944.2+89096.5
print(total_revenue)

109040.7


In [85]:
df_facil.head(10)

facid             name  membercost  guestcost  initialoutlay  \
0      0   Tennis Court 1         5.0       25.0          10000   
1      1   Tennis Court 2         5.0       25.0           8000   
2      2  Badminton Court         0.0       15.5           4000   
3      3     Table Tennis         0.0        5.0            320   
4      4   Massage Room 1         9.9       80.0           4000   
5      5   Massage Room 2         9.9       80.0           4000   
6      6     Squash Court         3.5       17.5           5000   
7      7    Snooker Table         0.0        5.0            450   
8      8       Pool Table         0.0        5.0            400   

   monthlymaintenance  
0                 200  
1                 200  
2                  50  
3                  10  
4                3000  
5                3000  
6                  80  
7                  15  
8                  15

In [86]:
from functools import reduce 
# df['quantity'].apply(lambda x: x*-1)
# pd.merge(product,customer,on='Product_ID')
df_facil['expenses']=df_facil['monthlymaintenance'].apply(lambda x: x*3)+df_facil['initialoutlay']
df_facil['total_monthly']=df_facil['monthlymaintenance'].apply(lambda x: x*3)

df_facil_all = reduce(lambda left , right:     # Merge three pandas DataFrames
                     pd.merge(left , right,
                              on = ["facid"]),
                     [df_memberfacil, df_facil, df_guestfacil])  
df_facil_all.head(10)

facid  member_total_cost             name  membercost  guestcost  \
0      0             4785.0   Tennis Court 1         5.0       25.0   
1      1             4410.0   Tennis Court 2         5.0       25.0   
2      2                0.0  Badminton Court         0.0       15.5   
3      3                0.0     Table Tennis         0.0        5.0   
4      4             8751.6   Massage Room 1         9.9       80.0   
5      5              534.6   Massage Room 2         9.9       80.0   
6      6             1463.0     Squash Court         3.5       17.5   
7      7                0.0    Snooker Table         0.0        5.0   
8      8                0.0       Pool Table         0.0        5.0   

   initialoutlay  monthlymaintenance  expenses  total_monthly  \
0          10000                 200     10600            600   
1           8000                 200      8600            600   
2           4000                  50      4150            150   
3            320                  10       350             30   
4           4000                3000     13000           9000   
5           4000                3000     13000           9000   
6           5000                  80      5240            240   
7            450                  15       495             45   
8            400                  15       445             45   

   guest_total_cost  
0            9075.0  
1            9900.0  
2            1906.5  
3             180.0  
4           41600.0  
5           13920.0  
6           12005.0  
7             240.0  
8             270.0

In [87]:
df_facil_all['total_revenue']=df_facil_all['member_total_cost']+df_facil_all['guest_total_cost']
df_facil_all.head(10)

facid  member_total_cost             name  membercost  guestcost  \
0      0             4785.0   Tennis Court 1         5.0       25.0   
1      1             4410.0   Tennis Court 2         5.0       25.0   
2      2                0.0  Badminton Court         0.0       15.5   
3      3                0.0     Table Tennis         0.0        5.0   
4      4             8751.6   Massage Room 1         9.9       80.0   
5      5              534.6   Massage Room 2         9.9       80.0   
6      6             1463.0     Squash Court         3.5       17.5   
7      7                0.0    Snooker Table         0.0        5.0   
8      8                0.0       Pool Table         0.0        5.0   

   initialoutlay  monthlymaintenance  expenses  total_monthly  \
0          10000                 200     10600            600   
1           8000                 200      8600            600   
2           4000                  50      4150            150   
3            320                  10       350             30   
4           4000                3000     13000           9000   
5           4000                3000     13000           9000   
6           5000                  80      5240            240   
7            450                  15       495             45   
8            400                  15       445             45   

   guest_total_cost  total_revenue  
0            9075.0        13860.0  
1            9900.0        14310.0  
2            1906.5         1906.5  
3             180.0          180.0  
4           41600.0        50351.6  
5           13920.0        14454.6  
6           12005.0        13468.0  
7             240.0          240.0  
8             270.0          270.0

In [88]:
df_facil_all['profit']=df_facil_all['total_revenue']-df_facil_all['expenses']
df_facil_all.head(10)

facid  member_total_cost             name  membercost  guestcost  \
0      0             4785.0   Tennis Court 1         5.0       25.0   
1      1             4410.0   Tennis Court 2         5.0       25.0   
2      2                0.0  Badminton Court         0.0       15.5   
3      3                0.0     Table Tennis         0.0        5.0   
4      4             8751.6   Massage Room 1         9.9       80.0   
5      5              534.6   Massage Room 2         9.9       80.0   
6      6             1463.0     Squash Court         3.5       17.5   
7      7                0.0    Snooker Table         0.0        5.0   
8      8                0.0       Pool Table         0.0        5.0   

   initialoutlay  monthlymaintenance  expenses  total_monthly  \
0          10000                 200     10600            600   
1           8000                 200      8600            600   
2           4000                  50      4150            150   
3            320                  10       350             30   
4           4000                3000     13000           9000   
5           4000                3000     13000           9000   
6           5000                  80      5240            240   
7            450                  15       495             45   
8            400                  15       445             45   

   guest_total_cost  total_revenue   profit  
0            9075.0        13860.0   3260.0  
1            9900.0        14310.0   5710.0  
2            1906.5         1906.5  -2243.5  
3             180.0          180.0   -170.0  
4           41600.0        50351.6  37351.6  
5           13920.0        14454.6   1454.6  
6           12005.0        13468.0   8228.0  
7             240.0          240.0   -255.0  
8             270.0          270.0   -175.0

In [89]:
all_expenses = df_facil['expenses'].sum(axis=0)
print(all_expenses)

55880


In [90]:
total_profit=109040.7-55880
print(total_profit)

53160.7


In [104]:
# Total revenue and overall profitability for the July - September period 

query = ''' SELECT f.name AS facility, f.guestcost * bookings.slots as profit
            FROM facilities AS f
            INNER JOIN bookings ON f.facid = bookings.facid
            GROUP BY facility
            ORDER BY profit
       '''
df = pd.read_sql_query(query, conn)
df.style.hide_index()            

C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\822008903.py:10: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df.style.hide_index()


In [107]:
query = ''' SELECT initialoutlay, monthlymaintenance
            FROM facilities
       '''
df = pd.read_sql_query(query, conn)
df.style.hide_index()   

C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\1714200688.py:5: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df.style.hide_index()


In [109]:
query = ''' 
            WITH expenses AS 
            (SELECT SUM(initialoutlay) AS total_outlay, SUM(monthlymaintenance * 3) AS total_maintenance
            FROM facilities)
            
            SELECT total_outlay, total_maintenance                   
            FROM expenses;            
       '''
df = pd.read_sql_query(query, conn)
df.style.hide_index()   

C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\3339673673.py:10: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df.style.hide_index()


In [117]:
query = ''' WITH rev_prof AS 
            (SELECT f.name AS facility,
            SUM(CASE WHEN bookings.memid != 0 THEN f.membercost * bookings.slots
    	            ELSE f.guestcost * bookings.slots END) AS revenue_per_fac
            FROM facilities AS f
            INNER JOIN bookings ON f.facid = bookings.facid
            GROUP BY facility)
            
            SELECT * from rev_prof
       '''

df = pd.read_sql_query(query, conn)
df.style.hide_index()            

C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\1946970066.py:13: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df.style.hide_index()


In [118]:
# Total revenue and overall profitability for the July - September period 

query = ''' WITH rev_prof AS 
            (SELECT f.name AS facility,
            SUM(CASE WHEN bookings.memid != 0 THEN f.membercost * bookings.slots
    	            ELSE f.guestcost * bookings.slots END) - (monthlymaintenance * 3) - (initialoutlay) AS profit
            FROM facilities AS f
            INNER JOIN bookings ON f.facid = bookings.facid
            GROUP BY facility 
            ORDER BY profit DESC)
            
            SELECT * FROM rev_prof
       '''

df = pd.read_sql_query(query, conn)
df.style.hide_index()       

C:\Users\avel8\AppData\Local\Temp\ipykernel_17608\1357041888.py:16: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  df.style.hide_index()


In [ ]:
# Total revenue and overall profitability for the July - September period 

query = ''' WITH rev_prof AS 
            (SELECT f.name AS facility,
            SUM(CASE WHEN bookings.memid != 0 THEN f.membercost * bookings.slots
    	            ELSE f.guestcost * bookings.slots END) AS revenue_per_fac,
            SUM(CASE WHEN bookings.memid != 0 THEN f.membercost * bookings.slots
    	            ELSE f.guestcost * bookings.slots END) - (monthlymaintenance * 3) - (initialoutlay) AS profit
            FROM facilities AS f
            INNER JOIN bookings ON f.facid = bookings.facid
            GROUP BY facility 
            ORDER BY profit DESC),

            expenses AS 
            (SELECT SUM(initialoutlay) AS total_outlay, SUM(monthlymaintenance * 3) AS total_maintenance
            FROM facilities)
            
            
            SELECT SUM(revenue_per_fac) AS total_revenue, 
                   total_outlay, total_maintenance, 
                   SUM(profit) AS total_profit
            FROM rev_prof,
                 expenses;
       '''

df = pd.read_sql_query(query, conn)
df.style.hide_index()            

In [ ]:
# Total revenue and overall profitability for the July - September period 

query = ''' WITH rev_prof AS 
            (SELECT f.name AS facility,
            SUM(CASE WHEN bookings.memid != 0 THEN f.membercost * bookings.slots
    	            ELSE f.guestcost * bookings.slots END) AS revenue_per_fac,
            SUM(CASE WHEN bookings.memid != 0 THEN f.membercost * bookings.slots
    	            ELSE f.guestcost * bookings.slots END) - (monthlymaintenance * 3) - (initialoutlay) AS profit
            FROM facilities AS f
            INNER JOIN bookings ON f.facid = bookings.facid
            GROUP BY facility 
            ORDER BY profit DESC),

            expenses AS 
            (SELECT SUM(initialoutlay) AS total_outlay, SUM(monthlymaintenance * 3) AS total_maintenance
            FROM facilities)
            
            
            SELECT SUM(revenue_per_fac) AS total_revenue, 
                   total_outlay, total_maintenance, 
                   SUM(profit) AS total_profit
            FROM rev_prof,
                 expenses;
       '''

df = pd.read_sql_query(query, conn)
df.style.hide_index()

Overall, we've made a profit of $53,160! Not bad for the first 3 months.

In [ ]:
# Examine the total revenue and profit for each facility for the period in question (July - Sep)
# Revenue minus monthly maintenance(times 3) & initial investment (initial outlay) = profit


In [ ]:
# Examine the total revenue and profit for each facility for the period in question (July - Sep)
# Revenue minus monthly maintenance(times 3) & initial investment (initial outlay) = profit

query = ''' SELECT f.name AS facility,
            SUM(CASE WHEN bookings.memid != 0 THEN f.membercost * bookings.slots
    	            ELSE f.guestcost * bookings.slots END) AS revenue,
            f.initialoutlay AS initial_investment,   
            f.monthlymaintenance * 3 AS maintenance_for_period,     
            SUM(CASE WHEN bookings.memid != 0 THEN f.membercost * bookings.slots
    	            ELSE f.guestcost * bookings.slots END) - (monthlymaintenance * 3) - (initialoutlay) AS profit
            FROM Facilities AS f
            INNER JOIN bookings ON f.facid = bookings.facid
            GROUP BY facility 
            ORDER BY profit DESC;
        '''

df = pd.read_sql_query(query, conn)
df.style.hide_index()

The most profitable facilities are Massage Room 1, Squash Court and Tennis Court 2 for the time period noted.  In contrast, the facilities with the greatest loss for the time period are the Badminton Court, Snooker Table and Pool Table (in order of greatest to least). Contributors to loss in each of these facilities can be attributed to pricing for members and guests.  

Our steepest loss (by far) is the Badminton Court.  This is because the initial investment was \$4,000 (the same as the Massages Rooms). However, it's free for members and only \$15 for guests. Whereas the Massage Room is \$10 for members and \$80 for guests. The monthly maintenance for the Badminton Court is only \$50 vs \$3000 for the Massage Rooms, so we expect it to become profitable over time due to low mainatenance cost. However we may want to look into increasing the price. 

Let's take a look at the average amount of bookings per member:

In [ ]:
# The count of bookings divided by the count of unique member id's

query = ''' SELECT (COUNT(b.bookid) / COUNT(DISTINCT memid)) AS bookings_per_member
            FROM bookings AS b;
            
        '''


df = pd.read_sql_query(query, conn)
df.style.hide_index()

Let's calculate the revenue per member:

In [ ]:
# Total revenue divided by total members 

query = ''' WITH revenue AS 
            (SELECT f.name AS facility,
            SUM(CASE WHEN bookings.memid != 0 THEN f.membercost * bookings.slots
    	            ELSE f.guestcost * bookings.slots END) AS revenue_per_fac
            FROM Facilities AS f
            INNER JOIN bookings ON f.facid = bookings.facid
            GROUP BY facility),

            member_count AS
            (SELECT COUNT(DISTINCT m.memid) AS mem
            FROM members AS m
            WHERE m.memid != 0 )

            SELECT (SUM(revenue_per_fac) /  mem)  AS revenue_per_member
            FROM revenue,
            member_count;
            
        '''

df = pd.read_sql_query(query, conn)
df.style.hide_index()

Let's calculate the revenue per booking:

In [ ]:
# Total revenue divided by total bookings 

query = ''' WITH revenue AS 
            (SELECT f.name AS facility,
            SUM(CASE WHEN bookings.memid != 0 THEN f.membercost * bookings.slots
    	            ELSE f.guestcost * bookings.slots END) AS revenue_per_fac
            FROM Facilities AS f
            INNER JOIN bookings ON f.facid = bookings.facid
            GROUP BY facility),

            booking_count AS
            (SELECT COUNT(DISTINCT bookid) AS count_
            FROM bookings)

            SELECT (SUM(revenue_per_fac) / count_) AS revenue_per_booking
            FROM revenue,
            booking_count;
            
        '''

df = pd.read_sql_query(query, conn)
df.style.hide_index()

Excellent! 

We are making \$3,634 per member and $27 per booking.

Now that we've examined our revenue/profit, let's make some more inquiries:

In [ ]:
# We are considering making some design changes to the the tennis courts. 
# Let's produce a list of all members who have used a tennis court to send out a phone survey. 

query = '''SELECT DISTINCT m.firstname || ' ' || m.surname AS name,
                  m.telephone AS contact,
		          Facilities.name AS facility
            FROM Members AS m 
            JOIN Bookings ON m.memid = Bookings.memid
            JOIN Facilities ON Facilities.facid = Bookings.facid
            WHERE Facilities.name LIKE 'Tennis%' AND m.firstname NOT LIKE 'Guest%'
            GROUP BY m.firstname
            ORDER BY name;
        '''


df = pd.read_sql_query(query, conn)
df.style.hide_index()

In [ ]:
# We would like to send out appreciation cards to members who have recommended others who in turn became new members!
# Let's produce a report of members and those who recommended them in alphabetical order

query = '''SELECT m.firstname || ' ' || m.surname AS 'new member',
		  m1.firstname || ' ' || m1.surname AS 'recommended by',
                  m1.address 
           FROM Members as m
           INNER JOIN Members as m1 
           ON m.recommendedby = m1.memid
           WHERE m1.memid != 0
           ORDER BY m.surname, m.firstname;
        '''

df = pd.read_sql_query(query, conn)
df.style.hide_index()

In [ ]:
# We would like to find the most popular facilities amongst our members
# Let's produce a list of the facilities with their total usage (booking count) over the 3 month period (guests not included)

query = ''' SELECT f.name AS 'Name', 
                   b.total AS Booking_count
            FROM Facilities AS f
            LEFT JOIN (SELECT facid, COUNT(bookid) AS total
            FROM Bookings AS b
            WHERE memid != 0
            GROUP BY facid) AS b 
            ON f.facid = b.facid
            ORDER BY Booking_count DESC;
        '''


df = pd.read_sql_query(query, conn)
df.style.hide_index()

In [ ]:
# Now let's find the most popular facilities amongst our members per month!

query = ''' SELECT CASE WHEN strftime('%m', b.starttime) = '07' THEN 'July'
                        WHEN strftime('%m', b.starttime) = '08' THEN 'August'
                        ELSE 'September' END AS Month, 
                    f.name AS Facility, 
                    COUNT(b.slots) AS Monthly_Usage
            FROM Bookings AS b
            LEFT JOIN Facilities AS f 
            ON f.facid = b.facid
            WHERE b.memid != 0      
            GROUP BY f.name, month 
            ORDER BY strftime('%m', b.starttime), Monthly_Usage DESC;
        '''


df = pd.read_sql_query(query, conn)
df.style.hide_index()

The Pool Tabel is consistently the most popular facility. This might be due to its low cost, popularity as a game, and the ability for people to socialize while playling. 

In [ ]:
# Let's view all bookings for September 14 where the booking cost was over $30

query = ''' SELECT b.bookid,
                   firstname || ' ' || surname AS Name,
                   f.name AS facility,
            CASE WHEN b.memid = 0 THEN f.guestcost * b.slots
                 ELSE f.membercost * b.slots END AS cost_of_booking
            FROM bookings AS b 
            JOIN facilities AS f ON b.facid = f.facid
            JOIN members AS m ON b.memid = m.memid
            WHERE b.starttime LIKE '2012-09-14%' AND cost_of_booking > 30
            ORDER BY cost_of_booking DESC;
        '''


df = pd.read_sql_query(query, conn)
df.style.hide_index()


On any given day, our guests pay more for services. This is simply because the pricing is significantly higher for non-members. 